name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v5

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Show flake
        run: nix --accept-flake-config flake show

      - name: Check flake
        run: nix --accept-flake-config flake check

      - name: Build aarch64 image
        run: nix --accept-flake-config build .#packages.aarch64-linux.attic
